#!/usr/bin/with-contenv bash

PHP_ERROR_REPORTING=${PHP_ERROR_REPORTING:-"E_ALL & ~E_DEPRECATED & ~E_NOTICE"}
sed -ri 's/^max_execution_time.*/max_execution_time = 60/g' /etc/php5/apache2/php.ini
sed -ri 's/^memory_limit.*/memory_limit = 256M/g' /etc/php5/apache2/php.ini
sed -ri 's/^memory_limit.*/memory_limit = 1024M/g' /etc/php5/cli/php.ini
sed -ri 's/^post_max_size.*/post_max_size = 1024M/g' /etc/php5/apache2/php.ini
sed -ri 's/^upload_max_filesize.*/upload_max_filesize = 1024M/g' /etc/php5/apache2/php.ini
sed -ri 's/^display_errors.*/display_errors = On/g' /etc/php5/apache2/php.ini
sed -ri 's/^display_errors.*/display_errors = On/g' /etc/php5/cli/php.ini
sed -ri "s/^error_reporting.*//g" /etc/php5/apache2/php.ini
sed -ri "s/^error_reporting.*//g" /etc/php5/cli/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/apache2/php.ini
echo "error_reporting = $PHP_ERROR_REPORTING" >> /etc/php5/cli/php.ini

source /etc/apache2/envvars && exec /usr/sbin/apache2 -DFOREGROUND
